### ISSUE TITLE
Guides to-do's

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-simple-resource#32]
- [ ] ~~Add comparison to other redux libs~~
- [ ] ~~Add guide about consistent/inconsistent APIs~~
- [x] Add "metadata" guide
- [x] xhr statuses
- [x] action types
  - [x] naming
  - [x] custom
  - [x] `replace`
- [x] customizing default reducer behavior
- [x] utils (#52)
- [ ] common patterns
- [x] add examples to naming (showing snakecasing taking place)

**Comment by jmeas** [comment]
Gonna close as most of these are in. I'll make a separate issue for the common patterns.
